// <auto-generated />
using System;
using EFCoreKnowledge.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreKnowledge.Api.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240824035824_StudentSeed")]
    partial class StudentSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.7.24405.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreKnowledge.Entities.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<bool>("IsRegularStudent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49b359fd-e37f-4dc2-a7d6-18393ccec5d8"),
                            Age = 25,
                            IsRegularStudent = true,
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("f8e9ce51-40e3-4bf3-a336-814b4e83775e"),
                            Age = 22,
                            IsRegularStudent = false,
                            Name = "Jane Doe"
                        },
                        new
                        {
                            Id = new Guid("014cebb0-f375-4a5b-bef4-bcc772debc28"),
                            Age = 30,
                            IsRegularStudent = true,
                            Name = "John Smith"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
